// CPC Palette with HW values
// Generated by mkts_om v0.2.20180904
// Copyleft 2017 by The Mojon Twins

const unsigned char my_inks [] = {
	0x14, // FF000000
	0x16, // FF008000
	0x12, // FF00FF00
	0x1A, // FF80FF00
	0x0A, // FFFFFF00
	0x03, // FFFFFF80
	0x07, // FFFF8080
	0x05, // FFFF0080
	0x1C, // FF800000
	0x0C, // FFFF0000
	0x0E, // FFFF8000
	0x06, // FF008080
	0x04, // FF000080
	0x17, // FF0080FF
	0x13, // FF00FFFF
	0x0B  // FFFFFFFF
};

